_core:
  default_config_hash: P2JFFcwppdagDcDp81m8FqSMKu2friuJaauLM6OCxwA
page_alter: false
raw_names: false
error_handlers:
  1: 1
rebuild_theme: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
devel_dumper: kint_extended
debug_logfile: 'temporary://drupal_debug.txt'
debug_pre: false
